friend/urls.py
from django.urls import path
from friend.views import (send_friend_request, accept_friend_request, get_all_users)

app_name = 'friend'
urlpatterns = [
    path('send_request/<user_id>', send_friend_request, name='send_request'),
    path('accept_request/<user_id>', accept_friend_request, name='accept_request'),
    path('all_users/', get_all_users, name='user_page'),
]

list_classes/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from . import views

app_name = 'list_classes'
urlpatterns = [
    path('update/', views.update_course_db, name="update"),
    path('comment/', include('comment.urls')),
    path('<str:subjects_displayed>/', views.IndexView.as_view(), name="classes"),
    path('description/<int:course_number>/', views.description, name='description'),
]

lous_list/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path
from django.views.generic import TemplateView
from .views import set_up_profile

urlpatterns = [
    path('', TemplateView.as_view(template_name='lous_list/home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls'), name='accounts'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('list_classes/', include('list_classes.urls'), name='list_classes'),
    path('search/', include('search.urls'), name='search'),
    path('friend/', include('friend.urls'), name='friend'),
    path('schedule/', include('schedule.urls'), name='schedule'),
    path('accounts/profile/<user_id>/', set_up_profile, name='profile'),
]

schedule/urls.py
from django.urls import path
from schedule.views import (add_course_to_schedule, delete_course_from_schedule)

app_name = 'schedule'
urlpatterns = [
    path('add_course/<course_number>', add_course_to_schedule, name='add_course'),
    path('delete_course/<course_number>', delete_course_from_schedule, name='delete_course'),

]

list_classes/models.py
from django.db import models
from django.contrib import admin


class Course(models.Model):
    # Instructor
    instructor_name = models.CharField(max_length=500, blank=True)
    instructor_email = models.CharField(max_length=500, blank=True)
    course_number = models.IntegerField(primary_key=True)   # Unique course number
    semester_code = models.IntegerField(null=True, blank=True)   # Code for semester (always starts with 1)
    course_section = models.CharField(max_length=500, blank=True) # 3 digit section number
    subject = models.CharField(max_length=500, blank=True)    # Mnemonic of class (ex: "CS" 1010)
    catalog_number = models.CharField(max_length=500, blank=True, default="")  # Number of class (ex: CS "1010")
    description = models.CharField(max_length=500)  # Name of class
    units = models.CharField(max_length=500, blank=True)  # Number of units (string)
    component = models.CharField(max_length=500, blank=True)  # LEC,DIS,etc.
    class_capacity = models.IntegerField(null=True, blank=True)
    wait_list = models.IntegerField(null=True, blank=True)
    wait_cap = models.IntegerField(null=True, blank=True)
    enrollment_total = models.IntegerField(null=True, blank=True)
    enrollment_available = models.IntegerField(null=True, blank=True)
    topic = models.CharField(max_length=500, blank=True)  # Not sure - usually empty string
    # Meetings
    meetings_days = models.CharField(max_length=500, blank=True)  # "MoWe" "TuTh" etc.
    meetings_start_time = models.CharField(max_length=500, blank=True)  # "17.00.00.000000-05:00"
    meetings_end_time = models.CharField(max_length=500, blank=True)  # "18.15.00.000000-05:00",
    meetings_facility_description = models.CharField(max_length=500, blank=True)  # "Olsson Hall 009"
    secondary_meetings_days = models.CharField(max_length=500, blank=True)  # "MoWe" "TuTh" etc.
    secondary_meetings_start_time = models.CharField(max_length=500, blank=True)  # "17.00.00.000000-05:00"
    secondary_meetings_end_time = models.CharField(max_length=500, blank=True)  # "18.15.00.000000-05:00",
    secondary_meetings_facility_description = models.CharField(max_length=500, blank=True)  # "Olsson Hall 009"

    def __str__(self):
        return self.description

list_classes/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Course

import requests


def description(request, course_number):
    course = get_object_or_404(Course, pk=course_number)
    # Only display LAB and DIS sections matching same catalog number and subject as lecture
    component_list = Course.objects.filter(component__in=['LAB', 'DIS'],
                                           catalog_number=course.catalog_number,
                                           subject=course.subject)
    return render(request, "list_classes/description.html", {'course': course,
                                                             'component_list': component_list})


class IndexView(generic.ListView):
    template_name = 'list_classes/index.html'
    context_object_name = 'course_list'
    subject_filter = []

    def get_queryset(self):
        # Sort data by catalog number/subject and only display LECTURE sections on index page
        self.subject_filter = []
        queryset = Course.objects.order_by('subject', 'catalog_number')
        queryset = queryset.filter(component__in=['LEC', 'IND'])

        # Change subjects displayed based on information from home screen
        # Display all subjects
        if self.kwargs['subjects_displayed'] == "all":
            subject_list = requests.get('http://luthers-list.herokuapp.com/api/deptlist/?format=json').json()
            for mnemonic in subject_list:
                mnemonic = mnemonic["subject"]
                self.subject_filter.append(mnemonic)

        # Add particular subject to subject filter dict
        else:
            self.subject_filter.append(self.kwargs['subjects_displayed'])

        # Display all subjects in subject filter dict
        queryset = queryset.filter(subject__in=self.subject_filter)
        return queryset


def update_course_db(request):

    # Add every class to the database
    subject_list = requests.get('http://luthers-list.herokuapp.com/api/deptlist/?format=json').json()
    for mnemonic in subject_list:
        mnemonic = mnemonic["subject"]
        print(mnemonic)
        luthers_list = requests.get('http://luthers-list.herokuapp.com/api/dept/' + mnemonic + '/?format=json').json()

        for c in luthers_list:
            course = Course(
                instructor_name = c['instructor']['name'],
                instructor_email = c['instructor']['email'],
                course_number = c['course_number'],
                semester_code = c['semester_code'],
                subject = c['subject'],
                catalog_number = c['catalog_number'],
                description = c['description'],
                units = c['units'],
                component = c['component'],
                class_capacity = c['class_capacity'],
                wait_list = c['wait_list'],
                wait_cap = c['wait_cap'],
                enrollment_total = c['enrollment_total'],
                enrollment_available = c['enrollment_available'],
                topic = c['topic'],
                # Set up default values for meeting
                meetings_days='-',
                meetings_start_time="",
                meetings_end_time="",
                meetings_facility_description='-',
                secondary_meetings_days='-',
                secondary_meetings_start_time="",
                secondary_meetings_end_time="",
                secondary_meetings_facility_description='-',
            )

            # Change Meetings values
            if len(c['meetings']) >= 1: # One or two meeting times
                course.meetings_days=c['meetings'][0]['days']
                course.meetings_start_time=c['meetings'][0]['start_time'][0:5].replace(".", ":")
                course.meetings_end_time=c['meetings'][0]['end_time'][0:5].replace(".", ":")
                course.meetings_facility_description=c['meetings'][0]['facility_description']
            if len(c['meetings']) == 2: # Two meeting times
                course.secondary_meetings_days=c['meetings'][1]['days']
                course.secondary_meetings_start_time=c['meetings'][1]['start_time'][0:5].replace(".", ":")
                course.secondary_meetings_end_time=c['meetings'][1]['end_time'][0:5].replace(".", ":")
                course.secondary_meetings_facility_description=c['meetings'][1]['facility_description']
            course.save()

    return HttpResponseRedirect(reverse(''))

templates/list_classes/description.html
<!DOCTYPE html>
<html lang="en">
{% include 'lous_list/base.html' %}

<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>{{ course.description }}</title>
    <link rel="stylesheet" href="{% static 'description.css' %}">
</head>
<body>
    <h1>Course Description</h1>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                {% if "warning" in message.tags %}
                    <p>{{ message }}</p>
                {% endif %}
            {% endfor %}
        </ul>
    {% endif %}
    <h1>{{ course.subject }} {{ course.catalog_number }} - {{ course.description }}</h1>
    <form method="GET" onclick=goBack()>
        {% csrf_token %}
        <input type="button" value="Back">
    </form>
    <p><b>Units: </b>{{ course.units }}<br>
    <b>Type: </b>{{ course.component }}<br>
    {% if course.meetings_days != "" %}
        <b>Days: </b>{{ course.meetings_days }}<br>
        <b>Time: </b>{{ course.meetings_start_time }} - {{ course.meetings_end_time }}<br>
    {% else %}
        <b>Days: </b>No dates have been assigned to this course.<br>
        <b>Time: </b>No times have been assigned to this course.<br>
    {% endif %}
    {% if course.secondary_meetings_days != "-" %}
        <b>Secondary Days: </b>{{ course.secondary_meetings_days }}<br>
        <b>Secondary Time: </b>{{ course.secondary_meetings_start_time }} - {{ course.secondary_meetings_end_time }}<br>
    {% endif %}
    {% if course.instructor_email != "" %}
        <b>Instructor: </b>{{course.instructor_name}} ({{ course.instructor_email }})<br>
    {% else %}
        <b>Instructor: </b>No instructor has been assigned to this course.<br>
    {% endif %}
    <b>Location: </b>{{ course.meetings_facility_description }}<br>
    <b>Enrollment Availability: </b>{{ course.enrollment_total }}/{{ course.class_capacity }}<br>
    <b>Course Number: </b>{{ course.course_number }}<br>
    {% if user.is_authenticated %}
        <form method="POST" action={% url 'schedule:add_course' course_number=course.course_number %}>
            {% csrf_token %}
            <input type="submit" value="Add Course to Schedule">
        </form>
    {% endif %}
    <section>
    <hr>
    {% if component_list %}
        <h3>Available Components:</h3>
        <ul>
            <form method="get" action="#">
                <select id="select_component" onchange="update()">
                    {% for component in component_list %}
                        <option id="selected_component" value="
                                                        <b>Units: </b>{{ component.units }}<br>
                                                        <b>Type: </b>{{ component.component }}<br>
                                                        {% if component.meetings_days != "" %}
                                                            <b>Days: </b>{{ component.meetings_days }}<br>
                                                            <b>Time: </b>{{ component.meetings_start_time }} - {{ component.meetings_end_time }}<br>
                                                        {% else %}
                                                            <b>Days: </b>No dates have been assigned to this course.<br>
                                                            <b>Time: </b>No times have been assigned to this course.<br>
                                                        {% endif %}
                                                        {% if component.secondary_meetings_days != "-" %}
                                                            Secondary Days: {{ component.secondary_meetings_days }}<br>
                                                            Secondary Time: {{ component.secondary_meetings_start_time }} - {{ course.secondary_meetings_end_time }}<br>
                                                        {% endif %}
                                                        {% if course.instructor_email != "" %}
                                                            <b>Instructor: </b>{{component.instructor_name}} ({{ component.instructor_email }})<br>
                                                        {% else %}
                                                            <b>Instructor: </b>No instructor has been assigned to this course.<br>
                                                        {% endif %}
                                                        <b>Location: </b>{{component.meetings_facility_description}}<br>
                                                        <b>Enrollment Availability: </b>{{ component.enrollment_total }}/{{ component.class_capacity }}<br>
                                                        <b>Course Number: </b>{{ component.course_number }}<br>">
                            {{component.meetings_days}} {{component.meetings_start_time}} - {{component.meetings_end_time}}</option>
                    {% endfor %}
                </select>
            </form>
            <p id="comp_header"></p>
            <script>
                function update() {
                    var select = document.getElementById('select_component');
                    var option = select.options[select.selectedIndex];
                    document.getElementById("comp_header").innerHTML = option.value;
                }
                update();
            </script>
        </ul>
        {% if user.is_authenticated %}
        <hr>
        <h3>Enroll in Component:</h3>
        <ul>
            {% for component in component_list %}
                <p>{{ component.meetings_days }} {{ component.meetings_start_time }} - {{ component.meetings_end_time }}, {{ component.meetings_facility_description }}</p>
                <a>
                    <form method="POST" action={% url 'schedule:add_course' course_number=component.course_number %}>
                        {% csrf_token %}
                        <input type="submit" value="Add Component to Schedule">
                    </form>
                </a>
            {% endfor %}
        </ul>
        {% endif %}
    {% else %}
        <h3>No components are available for this course.</h3>
    {% endif %}
    </section>
    {% include 'comment/description.html' %}
</body>
<script>
    function goBack() {
        if(document.referrer.includes(window.location.host)){
            window.history.back();
        }
    }
</script>
</html>

templates/list_classes/index.html
{% extends 'lous_list/base.html' %}
{% load static %}
{%block content %}
<link rel="stylesheet" href="{% static 'index.css' %}">
<head>
    <title>Lou's List</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"> -->
</head>
<main>
    <section>
        <h1>Courses:</h1>
    </section>
    <section>
    {% if course_list %}
        <ul style="list-style:none; background-color: #eeeeee;margin: 0px -30px 0px 0px;">
        {% for course in course_list %}
            <li style="background-color: #eeeeee">
                <div class="header"><a href="{% url 'list_classes:description' course_number=course.course_number %}">{{ course.subject }} {{ course.catalog_number }} - {{ course.description }}</a></div>
                <p><b>Units: </b>{{ course.units }}<br>
                <b>Type: </b>{{ course.component }}<br>
                {% if course.meetings_days != "" %}
                    <b>Days: </b>{{ course.meetings_days }}<br>
                    <b>Time: </b>{{ course.meetings_start_time }} - {{ course.meetings_end_time }}<br>
                {% else %}
                    <b>Days: </b>No dates have been assigned to this course.<br>
                    <b>Time: </b>No times have been assigned to this course.<br>
                {% endif %}
                {% if course.secondary_meetings_days != "-" %}
                    <b>Secondary Days: </b>{{ course.secondary_meetings_days }}<br>
                    <b>Secondary Time: </b>{{ course.secondary_meetings_start_time }} - {{ course.secondary_meetings_end_time }}<br>
                {% endif %}
                {% if course.instructor_email != "" %}
                    <b>Instructor: </b>{{course.instructor_name}} ({{ course.instructor_email }})<br>
                {% else %}
                    <b>Instructor: </b>No instructor has been assigned to this course.<br>
                {% endif %}
                    <b>Enrollment Availability: </b>{{ course.enrollment_total }}/{{ course.class_capacity }}</p>
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No classes are available.</p>
    {% endif %}
    </section>
</main>
{% endblock %}