friend/urls.py
from django.urls import path
from friend.views import (send_friend_request, accept_friend_request, get_all_users)

app_name = 'friend'
urlpatterns = [
    path('send_request/<user_id>', send_friend_request, name='send_request'),
    path('accept_request/<user_id>', accept_friend_request, name='accept_request'),
    path('all_users/', get_all_users, name='user_page'),
]

lous_list/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path
from django.views.generic import TemplateView
from .views import set_up_profile

urlpatterns = [
    path('', TemplateView.as_view(template_name='lous_list/home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls'), name='accounts'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('list_classes/', include('list_classes.urls'), name='list_classes'),
    path('search/', include('search.urls'), name='search'),
    path('friend/', include('friend.urls'), name='friend'),
    path('schedule/', include('schedule.urls'), name='schedule'),
    path('accounts/profile/<user_id>/', set_up_profile, name='profile'),
]

search/urls.py
from django.urls import path
from .views import SearchResultsView

"""
Title: Django Search Tutorial
Author: Will Vincent
Date: 10/31/2022
URL: https://learndjango.com/tutorials/django-search-tutorial
"""

app_name = 'search'
urlpatterns = [
    path("", SearchResultsView.as_view(), name="search"),
]

lous_list/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from schedule.views import get_schedule_courses


def set_up_profile(request, user_id):
    current_user = request.user

    # All user's friends
    current_user_friend_ids = []
    friend_list_query = current_user.friends.all()
    for friend_list in friend_list_query:
        current_user_friend_ids.append(friend_list.user_id)

    user = User.objects.get(id=user_id)
    courses = get_schedule_courses(request, user_id)
    return render(request, 'account/profile.html', {'current_user': current_user,
                                                    'current_user_friend_ids': current_user_friend_ids,
                                                    'user': user,
                                                    'courses': courses,})

templates/lous_list/base.html
<!DOCTYPE html>
<html style="margin: 0 0 20px 0">
<head>
    <title> Lou's List</title>
</head>

    <body style="background-color: #F7F9FF">
        {% include 'lous_list/topnav.html' %}

        {% block content %}

        {% endblock %}

        <!-- <footer>
            {%include 'lous_list/foot.html' %}
        </footer> -->
    </body>
</html>

templates/lous_list/foot.html
<footer class="foot">
    Copyright &copy; A-12
  </footer>

templates/lous_list/top-menu.html
{% load static %}
<nav class="navbar">
  <link rel="stylesheet" href="{% static 'style.css' %}">
    <div class="container">
      <a class="navbar-brand">
        <img src="{% static 'UVA_Logo.png' %}" alt="..." height="36">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.youtube.com/watch?v=dQw4w9WgXcQ">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  

templates/lous_list/topnav.html
{%load static %}
<nav class="navbar">
    <link rel="stylesheet" href="{% static 'base.css' %}">
    <!-- This section adds UVA Logo and if clicked redirects to home page -->
    <a href="/">
        <img src="{% static 'UVA_Logo.png' %}" alt="..." height="65">
    </a>
    <!-- This section adds the user page button. If clicked redirects to user page -->
    <div class="settings">
        <a href={% url "friend:user_page" %}>
            <img align="right" src="{% static 'friends.png' %}" alt="...">
        </a>
    </div>
    <!-- This section adds the profile button. If clicked redirects to profile page -->
    <div class="prof">
        {% if user.is_authenticated %}
            <a href='{% url 'profile' user_id=user.id%}'>
                <img align="right" src="{% static 'profile.png' %}" alt="...">
            </a>
        {% else %}
            <a href="/accounts/login"> <!-- If not logged in, takes you to login page -->
                <img align="right" src="{% static 'profile.png' %}" alt="...">
            </a>
        {% endif %}
    </div>
    <!-- Adds a search bar that redirects to whatever action form we have by clicking enter-->
    <div class="search-container">
        <form action={% url 'search:search' %} method="get" class='search-bar'>
            <input name="search_query" type="text" placeholder="" id="SearchBar">
            <button type="submit" class="searchButton"><img src="{% static 'search.png' %}"</button>
        </form>
    </div>

    {% if user.is_authenticated %}
        <script>
            var username="{{ user.username }}";
            document.getElementById("SearchBar").placeholder = "Searching as '" +username+"'";
        </script>
    {% else %}
        <script>
            document.getElementById("SearchBar").placeholder = "Searching as guest";
        </script>
    {% endif %}

</nav>