friend/urls.py
from django.urls import path
from friend.views import (send_friend_request, accept_friend_request, get_all_users)

app_name = 'friend'
urlpatterns = [
    path('send_request/<user_id>', send_friend_request, name='send_request'),
    path('accept_request/<user_id>', accept_friend_request, name='accept_request'),
    path('all_users/', get_all_users, name='user_page'),
]

lous_list/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path
from django.views.generic import TemplateView
from .views import set_up_profile

urlpatterns = [
    path('', TemplateView.as_view(template_name='lous_list/home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls'), name='accounts'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('list_classes/', include('list_classes.urls'), name='list_classes'),
    path('search/', include('search.urls'), name='search'),
    path('friend/', include('friend.urls'), name='friend'),
    path('schedule/', include('schedule.urls'), name='schedule'),
    path('accounts/profile/<user_id>/', set_up_profile, name='profile'),
]

friend/models.py
from django.contrib.auth.models import User
from django.db import models


class FriendList(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="friendlist")
    friends = models.ManyToManyField(User, blank=True, related_name="friends")

    def __str__(self):
        return self.user.username

    def add_friend(self, user):
        if user not in self.friends.all():
            self.friends.add(user)
            self.save()


class FriendRequest(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name="sender")
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name="receiver")
    is_active = models.BooleanField(blank=False, null=False, default=True)

    def __str__(self):
        return self.sender.username + " to " + self.receiver.username

friend/views.py
from django.shortcuts import render, redirect
from .models import FriendRequest, FriendList
from django.contrib import messages
from django.contrib.auth.models import User


def send_friend_request(request, user_id):
    sender = request.user
    receiver = User.objects.get(id=user_id)
    # Create friend lists for the sender and receiver if they don't have them already
    try:
        FriendList.objects.get(user=sender)
    except FriendList.DoesNotExist:
        FriendList.objects.create(user=sender)
    try:
        FriendList.objects.get(user=receiver)
    except FriendList.DoesNotExist:
        FriendList.objects.create(user=receiver)

    # Create a friend request if one doesn't already exist
    try:
        FriendRequest.objects.get(sender=sender, receiver=receiver)
        messages.success(request, "Friend request already sent.")
        return redirect("friend:user_page")
    except FriendRequest.DoesNotExist:
        FriendRequest.objects.create(sender=sender, receiver=receiver)
        messages.success(request, "Friend request sent.")
        return redirect("friend:user_page")


def accept_friend_request(request, user_id):
    receiver = request.user
    sender = User.objects.get(id=user_id)
    if sender in receiver.friends.all():
        messages.success(request, "Already friends.")
        return redirect("friend:user_page")
    try:
        friend_request = FriendRequest.objects.get(sender=sender, receiver=receiver)
        # If the friend request exists, add friends to each other's friend lists and delete it
        # Accept friend request and update sender and receiver
        receiver.friendlist.add_friend(sender)
        sender.friendlist.add_friend(receiver)
        friend_request.delete()
        messages.success(request, "Friend request accepted.")
        try:
            friend_request = FriendRequest.objects.get(sender=receiver, receiver=sender)
            friend_request.delete()
        except FriendRequest.DoesNotExist:
            pass
        return redirect("friend:user_page")
    except FriendRequest.DoesNotExist:
        messages.success(request, "No friend request found.")
        return redirect("friend:user_page")


def get_all_users(request):
    # Set up context variables
    if request.user.is_authenticated:
        # All Users
        users = User.objects.all()

        # All people that have sent requests to user
        received_friend_requests = FriendRequest.objects.filter(receiver=request.user)
        received_users = []
        for friend_request in received_friend_requests:
            received_users.append(friend_request.sender)

        # All people that current user has sent friends requests to
        sent_friend_requests = FriendRequest.objects.filter(sender=request.user)
        sent_users = []
        for friend_request in sent_friend_requests:
            sent_users.append(friend_request.receiver)

        # All user's friends
        friends = []
        friend_list_query = request.user.friends.all()
        for friend_list in friend_list_query:
            friends.append(friend_list.user_id)

        return render(request, 'friend/all_users_new.html', {'users': users,
                                                             'received_users': received_users,
                                                             'sent_users': sent_users,
                                                             'friends': friends})
    else:
        return render(request, 'friend/all_users_new.html')

templates/friend/all_usersR.html
<!DOCTYPE html>
<html lang="en">
{% include 'lous_list/base.html' %}
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Friend Page</title>
</head>
<body>
    <h1>Friend Request Page</h1>
    {% if user.is_authenticated %}
    <h1>Send Friend Requests</h1>
    <h2>Current User: {{ user.username }}</h2>
    {% for person in users %}
        <!-- If person is not current user -->
        {% if person.id != user.id %}
            <a href='{% url 'profile' user_id=person.id%}'>
                <h4>{{ person.username }}</h4>
            </a>
            <!-- Already friends -->
            {% if person.id in friends %}
                <form method="POST" action={%  url "friend:send_request" user_id=person.id %} >
                    {% csrf_token %}
                    <input type="button" value="You are Friends!">
                </form>
                <!-- Friend Request already sent -->
            {% elif person in sent_users %}
                <form method="POST" action={%  url "friend:send_request" user_id=person.id %} >
                    {% csrf_token %}
                    <input type="button" value="Friend Request Sent!">
                </form>
            <!-- Friend Request not already sent -->
            {% else %}
                <form method="POST" action={%  url "friend:send_request" user_id=person.id %} >
                    {% csrf_token %}
                    <input type="submit" value="Send Friend Request">
                </form>
            {% endif %}
            <!-- Accept button only appears if there is a request -->
            {% if person in received_users %}
                <form method="POST" action={% url 'friend:accept_request' user_id=person.id %}>
                    {% csrf_token %}
                    <input type="submit" value="Accept Friend Request">
                </form>
            {% endif %}
        {% endif %}
        <br/>
    {% endfor %}
    {% else %}
        <h1>Please log in first before you view other users.</h1>
        <form>
            {% csrf_token %}
            <input type="button" value="Back" onclick="history.back()">
        </form>
    {% endif %}
</body>

</html>

templates/friend/all_users_new.html
{% extends 'lous_list/base.html' %}
{%load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'homes.css' %}">
<div class="accordionF">
    <h1>Users Page</h1>
    <div class="accordion-item">
      <div class="accordion-item-header">Friends</div>
      <div class="accordion-item-body">
        <div class="accordion-item-body-content">
            {% if user.is_authenticated %}
                {% for person in users %}
                    {% if person.id in friends %}
                        <ul>
                        {% if person.id != user.id %}
                        <hr>
                            <li>
                                <a>{{person.username}}</a>
                                <a href='{% url 'profile' user_id=person.id%}'>
                                    <button class='profileLink'>{{person.username}}'s Profile</button>
                                </a>
                            </li>
                        </ul>
                        {% endif %}
                    {% endif %}
                {% endfor %}
                <hr>
            {% else %}
                <p>You must be logged in to see other users.</p>
            {% endif %}
        </div>
      </div>
    </div>
    <div class="accordion-item">
        <div class="accordion-item-header">All Users</div>
        <div class="accordion-item-body">
          <div class="accordion-item-body-content">
            {% if user.is_authenticated %}
                {% for person in users %}
                    {% if person.id not in friends %}
                        <ul>
                        <hr>
                            <li>
                                <a>{{person.username}}</a>
                                    <a>
                                        {% if person.id != user.id %}
                                            {% if person in sent_users %}
                                                <form method="POST" action={%  url "friend:send_request" user_id=person.id %} >
                                                    {% csrf_token %}
                                                    <input class="sent" type="button" value="Friend Request Sent!">
                                                </form>
                                            <!-- Friend Request not already sent -->
                                            {% else %}
                                                <form method="POST" action={%  url "friend:send_request" user_id=person.id %} >
                                                    {% csrf_token %}
                                                    <input class="send" type="submit" value="Send Friend Request">
                                                </form>
                                            {% endif %}
                                            <!-- Accept button only appears if there is a request -->
                                            {% if person in received_users %}
                                                <form method="POST" action={% url 'friend:accept_request' user_id=person.id %}>
                                                    {% csrf_token %}
                                                    <input class="accept" type="submit" value="Accept Friend Request">
                                                </form>
                                            {% endif %}
                                        {% endif %}
                                    </a>
                            </li>
                        </ul>
                    {% endif %}
                {% endfor %}
                <hr>
            {% else %}
                <p>You must be logged in to see other users.</p>
            {% endif %}
          </div>
        </div>
      </div>
  </div>

<script>
    const accordionItemHeaders = document.querySelectorAll(".accordion-item-header");
    accordionItemHeaders.forEach(accordionItemHeader => {
    accordionItemHeader.addEventListener("click", event => {

        accordionItemHeader.classList.toggle("active");
        const accordionItemBody = accordionItemHeader.nextElementSibling;
        if(accordionItemHeader.classList.contains("active")) {
        accordionItemBody.style.maxHeight = accordionItemBody.scrollHeight + "px";
        }
        else {
        accordionItemBody.style.maxHeight = 0;
        }  
    });
    });
</script>

{% endblock %}

templates/friend/all_users_newI.html
<!DOCTYPE html>
<html lang="en">
    <head>
      {% load static %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'accounts/profile.css' %}">
        <title>Users Page</title>
    </head>
    <body>
    <div class="main">
        <div class='head'>
            <div class='buttonWrapper'>
                <form class='returnForm' method="GET" action={% url 'home' %}>
                    {% csrf_token %}
                    <div class="returnButton">
                        <input class='return' type="submit" value="<" align='left'>
                    </div>
                </form>
            </div>
            <div class='headerWrapper'>
                <h1>Users Page</h1>
                <hr>
            </div>
        </div>
        {% if user.is_authenticated %}
        {% for person in users %}
            <!-- If person is not current user -->
            {% if person.id != user.id %}
                <a href='{% url 'profile' user_id=person.id%}'>
                    <h2>{{ person.username }}</h2>
                </a>
                <!-- Already friends -->
                {% if person.id in friends %}
                    <form method="POST" action={%  url "friend:send_request" user_id=person.id %} >
                        {% csrf_token %}
                        <input class="friends" type="button" value="You are Friends!">
                    </form>
                    <!-- Friend Request already sent -->
                {% elif person in sent_users %}
                    <form method="POST" action={%  url "friend:send_request" user_id=person.id %} >
                        {% csrf_token %}
                        <input class="sent" type="button" value="Friend Request Sent!">
                    </form>
                <!-- Friend Request not already sent -->
                {% else %}
                    <form method="POST" action={%  url "friend:send_request" user_id=person.id %} >
                        {% csrf_token %}
                        <input class="send" type="submit" value="Send Friend Request">
                    </form>
                {% endif %}
                <!-- Accept button only appears if there is a request -->
                {% if person in received_users %}
                    <form method="POST" action={% url 'friend:accept_request' user_id=person.id %}>
                        {% csrf_token %}
                        <input class="accept" type="submit" value="Accept Friend Request">
                    </form>
                {% endif %}
                <br>
            {% endif %}
        {% endfor %}
        {% else %}
            <h1>Please log in first before you view other users.</h1>
            <form>
                {% csrf_token %}
                <input type="button" value="Back" onclick="history.back()">
            </form>
        {% endif %}
        </div>
    </body>
</html>